<a href="https://colab.research.google.com/github/DangerDR0519/NeuralNetworks/blob/main/ICP-2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [16]:
class Employee:
    # Class variable to count the number of Employees
    employee_count = 0

    def __init__(self, name, family, salary, department):
        # Instance variables
        self.name = name
        self.family = family
        self.salary = salary
        self.department = department

        # Increment the employee count
        Employee.employee_count += 1

    @classmethod
    def average_salary(cls, employee_list):
        # Calculate average salary from a list of employees
        total_salary = sum(emp.salary for emp in employee_list)
        return total_salary / len(employee_list) if employee_list else 0

    @classmethod
    def get_employee_count(cls):
        # Return the number of employees
        return cls.employee_count

    def display_info(self):
        # Display the information of the employee
        return f"Name: {self.name}, Family: {self.family}, Salary: {self.salary}, Department: {self.department}"

# FulltimeEmployee class inherits from Employee
class FulltimeEmployee(Employee):
    def __init__(self, name, family, salary, department, benefits):
        # Initialize the base class
        super().__init__(name, family, salary, department)
        # Additional attribute for full-time employees
        self.benefits = benefits

    def display_info(self):
        # Display the information of the full-time employee
        base_info = super().display_info()
        return f"{base_info}, Benefits: {self.benefits}"

# Create instances of Employee and FulltimeEmployee
emp1 = Employee("Durga", "Rao", 50000, "HR")
emp2 = Employee("sri", "kanth", 60000, "IT")
ft_emp1 = FulltimeEmployee("sai", "teja", 70000, "Finance", "Health Insurance")
ft_emp2 = FulltimeEmployee("anji", "babu", 80000, "IT", "Retirement Plan")

# List of employees for average salary calculation
employee_list = [emp1, emp2, ft_emp1, ft_emp2]

# Display employee information
print(emp1.display_info())
print(emp2.display_info())
print(ft_emp1.display_info())
print(ft_emp2.display_info())

# Display average salary
print("Average Salary:", Employee.average_salary(employee_list))

# Display total number of employees
print("Total Number of Employees:", Employee.get_employee_count())


Name: Durga, Family: Rao, Salary: 50000, Department: HR
Name: sri, Family: kanth, Salary: 60000, Department: IT
Name: sai, Family: teja, Salary: 70000, Department: Finance, Benefits: Health Insurance
Name: anji, Family: babu, Salary: 80000, Department: IT, Benefits: Retirement Plan
Average Salary: 65000.0
Total Number of Employees: 4


In [8]:
import numpy as np

# Step 1: Create a random vector of size 20 with floats in the range 1-20
vector = np.random.uniform(1, 20, 20)

# Step 2: Reshape the vector to a 4x5 array
matrix = vector.reshape(4, 5)

# Step 3: Replace the maximum value in each row with 0 (axis=1)
# Find the index of the maximum values in each row
max_indices = np.argmax(matrix, axis=1)

# Use advanced indexing to replace the maximum values with 0
matrix[np.arange(matrix.shape[0]), max_indices] = 0

# Output the matrix
print("Matrix after replacing max values with 0:")
print(matrix)


Matrix after replacing max values with 0:
[[ 2.85195292 14.06382485  8.21948926  0.          4.49984022]
 [12.3630968  14.76851791  3.18145073 10.23349653  0.        ]
 [ 6.39046861 14.08268853  0.         17.15711728  9.89809466]
 [15.24933971  4.70601002  0.         10.29456839  5.09476999]]
